const City = [
  {
    "name": "Bergen op Zoom",
    "province": "Noord-Brabant",
    "longitude": 4.296232,
    "latitude": 51.495152,
    "altitude": 6,
    "inwoners": 70570,
    "establish": 1198,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 2,
    "reizigers": 5548
  },
  {
    "name": "Breda",
    "province": "Noord-Brabant",
    "longitude": 4.779902,
    "latitude": 51.59542,
    "altitude": 2.5,
    "inwoners": 151765,
    "establish": 1125,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "Y",
    "perrons": 6,
    "reizigers": 36131
  },
  {
    "name": "Eindhoven",
    "province": "Noord-Brabant",
    "longitude": 5.480489,
    "latitude": 51.443111,
    "altitude": 16,
    "inwoners": 241671,
    "establish": 1232,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "N",
    "perrons": 6,
    "reizigers": 63532
  },
  {
    "name": "Helmond",
    "province": "Noord-Brabant",
    "longitude": 5.661424,
    "latitude": 51.475719,
    "altitude": 18.6,
    "inwoners": 96932,
    "establish": 1179,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 2,
    "reizigers": 6474
  },
  {
    "name": "s-Hertogenbosch",
    "province": "Noord-Brabant",
    "longitude": 5.294126,
    "latitude": 51.690311,
    "altitude": 6.3,
    "inwoners": 112850,
    "establish": 1185,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "N",
    "perrons": 5,
    "reizigers": 56752
  },
  {
    "name": "Oss",
    "province": "Noord-Brabant",
    "longitude": 5.530234,
    "latitude": 51.765051,
    "altitude": 8,
    "inwoners": 57740,
    "establish": 1161,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 2,
    "reizigers": 7012
  },
  {
    "name": "Roosendaal",
    "province": "Noord-Brabant",
    "longitude": 4.4583499,
    "latitude": 51.5400231,
    "altitude": 3.5,
    "inwoners": 67320,
    "establish": 1266,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 3,
    "reizigers": 11359
  },
  {
    "name": "Tilburg",
    "province": "Noord-Brabant",
    "longitude": 5.083128,
    "latitude": 51.560395,
    "altitude": 14.5,
    "inwoners": 203690,
    "establish": 1191,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "Y",
    "perrons": 3,
    "reizigers": 31144
  },
  {
    "name": "Goes",
    "province": "Zeeland",
    "longitude": 3.890832,
    "latitude": 51.498255,
    "altitude": 2,
    "inwoners": 29420,
    "establish": 900,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 2,
    "reizigers": 5786
  },
  {
    "name": "Middelburg",
    "province": "Zeeland",
    "longitude": 3.618074,
    "latitude": 51.495416,
    "altitude": 3,
    "inwoners": 43165,
    "establish": 850,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 2,
    "reizigers": 3962
  },
  {
    "name": "Vlissingen",
    "province": "Zeeland",
    "longitude": 3.595489,
    "latitude": 51.445276,
    "altitude": 4,
    "inwoners": 45846,
    "establish": 1247,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 2,
    "reizigers": 1889
  },
  {
    "name": "Heerlen",
    "province": "Limburg",
    "longitude": 5.975332,
    "latitude": 50.890779,
    "altitude": 113,
    "inwoners": 87614,
    "establish": 0,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 4,
    "reizigers": 3819
  },
  {
    "name": "Maastricht",
    "province": "Limburg",
    "longitude": 5.705387,
    "latitude": 50.851203,
    "altitude": 50,
    "inwoners": 124673,
    "establish": -10,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 6,
    "reizigers": 9791
  },
  {
    "name": "Roermond",
    "province": "Limburg",
    "longitude": 5.994926,
    "latitude": 51.193127,
    "altitude": 30,
    "inwoners": 42280,
    "establish": 250,
    "glazenHuis": "N",
    "hanze": "Y",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 3,
    "reizigers": 8967
  },
  {
    "name": "Sittard",
    "province": "Limburg",
    "longitude": 5.858378,
    "latitude": 51.001661,
    "altitude": 53,
    "inwoners": 37490,
    "establish": 650,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 4,
    "reizigers": 8078
  },
  {
    "name": "Venlo",
    "province": "Limburg",
    "longitude": 6.171651,
    "latitude": 51.365241,
    "altitude": 24,
    "inwoners": 69440,
    "establish": 890,
    "glazenHuis": "N",
    "hanze": "Y",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 5,
    "reizigers": 3072
  },
  {
    "name": "Weert",
    "province": "Limburg",
    "longitude": 5.702543,
    "latitude": 51.248596,
    "altitude": 38,
    "inwoners": 45580,
    "establish": 1062,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 2,
    "reizigers": 6738
  },
  {
    "name": "Arnhem",
    "province": "Gelderland",
    "longitude": 5.903028,
    "latitude": 51.984739,
    "altitude": 30,
    "inwoners": 171225,
    "establish": 893,
    "glazenHuis": "N",
    "hanze": "Y",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 8,
    "reizigers": 43362
  },
  {
    "name": "Apeldoorn",
    "province": "Gelderland",
    "longitude": 5.969322,
    "latitude": 52.209359,
    "altitude": 18,
    "inwoners": 141255,
    "establish": 792,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 4,
    "reizigers": 12590
  },
  {
    "name": "Ede",
    "province": "Gelderland",
    "longitude": 5.672117,
    "latitude": 52.027866,
    "altitude": 24,
    "inwoners": 79435,
    "establish": 1216,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 3,
    "reizigers": 15346
  },
  {
    "name": "Harderwijk",
    "province": "Gelderland",
    "longitude": 5.619816,
    "latitude": 52.337513,
    "altitude": 6,
    "inwoners": 50496,
    "establish": 1231,
    "glazenHuis": "N",
    "hanze": "Y",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 2,
    "reizigers": 4840
  },
  {
    "name": "Nijmegen",
    "province": "Gelderland",
    "longitude": 5.853124,
    "latitude": 51.843633,
    "altitude": 26,
    "inwoners": 188971,
    "establish": -10,
    "glazenHuis": "Y",
    "hanze": "Y",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 4,
    "reizigers": 39943
  },
  {
    "name": "Zutphen",
    "province": "Gelderland",
    "longitude": 6.195577,
    "latitude": 52.145334,
    "altitude": 12,
    "inwoners": 40150,
    "establish": 325,
    "glazenHuis": "N",
    "hanze": "Y",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 3,
    "reizigers": 10763
  },
  {
    "name": "Amersfoort",
    "province": "Utrecht",
    "longitude": 5.373819,
    "latitude": 52.153845,
    "altitude": 10,
    "inwoners": 163896,
    "establish": 1028,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 6,
    "reizigers": 43123
  },
  {
    "name": "Utrecht",
    "province": "Utrecht",
    "longitude": 5.110094,
    "latitude": 52.089005,
    "altitude": 7,
    "inwoners": 376982,
    "establish": 50,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "N",
    "perrons": 16,
    "reizigers": 229788
  },
  {
    "name": "Woerden",
    "province": "Utrecht",
    "longitude": 4.892993,
    "latitude": 52.084905,
    "altitude": 3,
    "inwoners": 54120,
    "establish": 41,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 4,
    "reizigers": 13157
  },
  {
    "name": "Alkmaar",
    "province": "Noord-Holland",
    "longitude": 4.740363,
    "latitude": 52.637866,
    "altitude": 5,
    "inwoners": 113142,
    "establish": 850,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "N",
    "perrons": 5,
    "reizigers": 15272
  },
  {
    "name": "Amsterdam",
    "province": "Noord-Holland",
    "longitude": 4.899157,
    "latitude": 52.379407,
    "altitude": 7,
    "inwoners": 938969,
    "establish": 1275,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "Y",
    "perrons": 11,
    "reizigers": 171272
  },
  {
    "name": "Den Helder",
    "province": "Noord-Holland",
    "longitude": 4.760657,
    "latitude": 52.95672,
    "altitude": 2,
    "inwoners": 56639,
    "establish": 1500,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 3,
    "reizigers": 3140
  },
  {
    "name": "Enkhuizen",
    "province": "Noord-Holland",
    "longitude": 5.288552,
    "latitude": 52.699626,
    "altitude": 2,
    "inwoners": 18795,
    "establish": 1356,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 2,
    "reizigers": 1607
  },
  {
    "name": "Haarlem",
    "province": "Noord-Holland",
    "longitude": 4.637049,
    "latitude": 52.388069,
    "altitude": 6,
    "inwoners": 168981,
    "establish": 948,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "Y",
    "perrons": 6,
    "reizigers": 36507
  },
  {
    "name": "Hilversum",
    "province": "Noord-Holland",
    "longitude": 5.181741,
    "latitude": 52.226298,
    "altitude": 9,
    "inwoners": 94726,
    "establish": 900,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 5,
    "reizigers": 25012
  },
  {
    "name": "Hoorn",
    "province": "Noord-Holland",
    "longitude": 5.054224,
    "latitude": 52.645083,
    "altitude": 2,
    "inwoners": 76074,
    "establish": 716,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 3,
    "reizigers": 12896
  },
  {
    "name": "Schiphol",
    "province": "Noord-Holland",
    "longitude": 4.761784,
    "latitude": 52.309215,
    "altitude": 0,
    "inwoners": 90,
    "establish": 1848,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 6,
    "reizigers": 90108
  },
  {
    "name": "Delft",
    "province": "Zuid-Holland",
    "longitude": 4.355986,
    "latitude": 52.007437,
    "altitude": 4,
    "inwoners": 109978,
    "establish": 1150,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 2,
    "reizigers": 34989
  },
  {
    "name": "Den Haag",
    "province": "Zuid-Holland",
    "longitude": 4.324611,
    "latitude": 52.080729,
    "altitude": 6,
    "inwoners": 568118,
    "establish": 1230,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "Y",
    "perrons": 12,
    "reizigers": 80091
  },
  {
    "name": "Dordrecht",
    "province": "Zuid-Holland",
    "longitude": 4.668574,
    "latitude": 51.807105,
    "altitude": 5,
    "inwoners": 122950,
    "establish": 1120,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 7,
    "reizigers": 20360
  },
  {
    "name": "Gouda",
    "province": "Zuid-Holland",
    "longitude": 4.706138,
    "latitude": 52.017307,
    "altitude": 2,
    "inwoners": 77348,
    "establish": 1143,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 5,
    "reizigers": 28246
  },
  {
    "name": "Leiden",
    "province": "Zuid-Holland",
    "longitude": 4.482019,
    "latitude": 52.165562,
    "altitude": 6,
    "inwoners": 130381,
    "establish": 860,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 6,
    "reizigers": 80409
  },
  {
    "name": "Rotterdam",
    "province": "Zuid-Holland",
    "longitude": 4.468677,
    "latitude": 51.924951,
    "altitude": 2,
    "inwoners": 600015,
    "establish": 1270,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "Y",
    "perrons": 13,
    "reizigers": 104840
  },
  {
    "name": "Almere",
    "province": "Flevoland",
    "longitude": 5.218173,
    "latitude": 52.374897,
    "altitude": 0,
    "inwoners": 231921,
    "establish": 1976,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 4,
    "reizigers": 26979
  },
  {
    "name": "Lelystad",
    "province": "Flevoland",
    "longitude": 5.472992,
    "latitude": 52.507869,
    "altitude": -2,
    "inwoners": 85337,
    "establish": 1967,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 4,
    "reizigers": 12592
  },
  {
    "name": "Almelo",
    "province": "Overijssel",
    "longitude": 6.654461,
    "latitude": 52.357819,
    "altitude": 13,
    "inwoners": 75030,
    "establish": 1050,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "N",
    "perrons": 3,
    "reizigers": 6544
  },
  {
    "name": "Deventer",
    "province": "Overijssel",
    "longitude": 6.161428,
    "latitude": 52.257002,
    "altitude": 11,
    "inwoners": 82960,
    "establish": 768,
    "glazenHuis": "N",
    "hanze": "Y",
    "landskampioen": "Y",
    "dierentuin": "N",
    "perrons": 3,
    "reizigers": 20355
  },
  {
    "name": "Enschede",
    "province": "Overijssel",
    "longitude": 6.889714,
    "latitude": 52.222345,
    "altitude": 45,
    "inwoners": 161981,
    "establish": 1119,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "Y",
    "dierentuin": "N",
    "perrons": 5,
    "reizigers": 8334
  },
  {
    "name": "Hengelo",
    "province": "Overijssel",
    "longitude": 6.794238,
    "latitude": 52.261975,
    "altitude": 21,
    "inwoners": 83982,
    "establish": 1188,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 3,
    "reizigers": 5740
  },
  {
    "name": "Zwolle",
    "province": "Overijssel",
    "longitude": 6.092274,
    "latitude": 52.504954,
    "altitude": 4,
    "inwoners": 133863,
    "establish": 1040,
    "glazenHuis": "Y",
    "hanze": "Y",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 14,
    "reizigers": 42976
  },
  {
    "name": "Assen",
    "province": "Drenthe",
    "longitude": 6.571148,
    "latitude": 52.991746,
    "altitude": 13,
    "inwoners": 70761,
    "establish": 1259,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 3,
    "reizigers": 7548
  },
  {
    "name": "Meppel",
    "province": "Drenthe",
    "longitude": 6.197791,
    "latitude": 52.691777,
    "altitude": 5,
    "inwoners": 36546,
    "establish": 1141,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 3,
    "reizigers": 6386
  },
  {
    "name": "Groningen",
    "province": "Groningen",
    "longitude": 6.563955,
    "latitude": 53.210549,
    "altitude": 5,
    "inwoners": 243663,
    "establish": 1040,
    "glazenHuis": "Y",
    "hanze": "Y",
    "landskampioen": "Y",
    "dierentuin": "N",
    "perrons": 11,
    "reizigers": 16064
  },
  {
    "name": "Heerenveen",
    "province": "Friesland",
    "longitude": 5.915327,
    "latitude": 52.960693,
    "altitude": 3,
    "inwoners": 51960,
    "establish": 1551,
    "glazenHuis": "N",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "N",
    "perrons": 2,
    "reizigers": 4987
  },
  {
    "name": "Leeuwarden",
    "province": "Friesland",
    "longitude": 5.792655,
    "latitude": 53.196207,
    "altitude": 4,
    "inwoners": 129784,
    "establish": 750,
    "glazenHuis": "Y",
    "hanze": "N",
    "landskampioen": "N",
    "dierentuin": "Y",
    "perrons": 7,
    "reizigers": 7705
  }
]